(function () {
    'use strict';

    // --- ГЛОБАЛЬНІ КОНСТАНТИ ---
    const COMPONENT_NAME = 'interface_tools_plugin';
    const SETTINGS_TAB_NAME = 'interface_tools';
    const SETTINGS_TAB_TITLE = 'Interface Tools';
    const SETTINGS_STORAGE_KEY = 'plugin_interface_tools_settings'; // Ключ для збереження налаштувань

    // --- ФУНКЦІЯ ВІДМАЛЬОВУВАННЯ ВМІСТУ ВКЛАДКИ ---

    /**
     * @brief Функція, яка відмальовує вміст нашої нової сторінки налаштувань.
     * @param {object} component - Об'єкт компонента, який надає Lampa.
     */
    function renderSettingsPage(component) {
        // Отримуємо поточні збережені налаштування
        let user_settings = Lampa.Storage.get(SETTINGS_STORAGE_KEY, { 
            test_option_enabled: false 
        });

        // Створюємо контейнер для налаштувань
        let container = document.createElement('div');
        container.innerHTML = `
            <div class="settings-block">
                <div class="settings-block__title">Налаштування Інструментів Інтерфейсу</div>
                <div class="settings-block__description">Тут ви можете керувати власними інструментами інтерфейсу.</div>
                
                <div class="settings-block__item" data-name="test_option_enabled">
                    <div class="settings-block__name">Увімкнути Тестовий Інструмент</div>
                    <div class="settings-block__value"></div> </div>
                
            </div>
        `;
        
        // 1. Додаємо HTML-контейнер до компонента Lampa
        component.element.append(container);

        // 2. Створюємо інтерактивний перемикач (Toggle)
        const toggle_container = component.element.querySelector('[data-name="test_option_enabled"] .settings-block__value');
        
        // Створюємо новий компонент Toggle Lampa
        let toggle = new Lampa.Toggle({
            on: user_settings.test_option_enabled, // Початковий стан згідно зі сховищем
            callback: function (value) {
                // Ця функція викликається щоразу, коли користувач змінює стан перемикача
                
                // Оновлюємо налаштування
                user_settings.test_option_enabled = value;
                
                // Зберігаємо оновлені налаштування в Lampa.Storage
                Lampa.Storage.set(SETTINGS_STORAGE_KEY, user_settings);
                
                // Тут можна додати код, що виконує дію (наприклад, змінює вигляд інтерфейсу)
                console.log(`[${COMPONENT_NAME}] Стан опції змінено на: ${value}`);
            }
        });

        // Додаємо Toggle до його контейнера в HTML
        toggle_container.append(toggle.render());

        // Опціонально: фокусування для навігації
        component.listener.follow(toggle_container);
    }

    // --- ФУНКЦІЯ ІНІЦІАЛІЗАЦІЇ ПЛАГІНА ---

    /**
     * @brief Запускається при ініціалізації плагіна
     */
    function init() {
        console.log(`[${COMPONENT_NAME}] Плагін ініціалізовано. Версія: 1.0.0`);

        if (window.Lampa && Lampa.Settings) {
            
            // Об'єкт, що описує нашу нову вкладку
            let new_tab_page = {
                title: SETTINGS_TAB_TITLE, 
                component: COMPONENT_NAME, 
                onRender: renderSettingsPage 
            };

            // Додаємо вкладку в налаштування
            Lampa.Settings.add(new_tab_page, { 
                // Вставляємо після вкладки 'interface'
                after: 'interface' 
            });

            console.log(`[${COMPONENT_NAME}] Вкладку "${SETTINGS_TAB_TITLE}" додано.`);
        } else {
            console.error(`[${COMPONENT_NAME}] Lampa.Settings не доступний! Перевірте версію Lampa.`);
        }
    }


    // --- РЕЄСТРАЦІЯ КОМПОНЕНТА В LAMPА ---
    
    Lampa.Component.add({
        component: COMPONENT_NAME,
        version: '1.0.0',
        author: 'Generated by Gemini',
        passive: true, 
        methods: {
            init: init 
        }
    });

})();
